/*
  ═══════════════════════════════════════════════════════════════════
  ACCOUNTS PAGE - Manage Bank Accounts
  ═══════════════════════════════════════════════════════════════════
  
  This page allows users to:
  - View all their bank accounts (checking, savings, credit cards, investments)
  - Add new accounts with details (name, type, balance, institution, last 4 digits)
  - Delete existing accounts
  - See visual cards for each account with color-coded gradients
  
  Data Flow:
  1. User must be logged in (checked via Supabase session)
  2. Page fetches all accounts from Supabase 'accounts' table
  3. User can toggle form to add new account
  4. Form data is validated and saved to database
  5. Account list refreshes automatically after add/delete
  
  Database Table: accounts
  - Columns: id, user_id, name, type, balance, account_number_last_four, institution_name, created_at
  - RLS Policy: Users can only see/modify their own accounts
*/

'use client'

import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import { createClient } from "@/lib/supabase"
import { AppSidebar } from "@/components/app-sidebar"
import { AccountCard } from "@/components/account-card"
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"
import { Separator } from "@/components/ui/separator"
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"

// ═══════════════════════════════════════════════════════════════════
// TYPE DEFINITIONS
// ═══════════════════════════════════════════════════════════════════

// TypeScript interface defining the structure of an Account object
// This matches the columns in the Supabase 'accounts' table
interface Account {
  id: string                         // UUID generated by Supabase
  name: string                       // Name (e.g., "My Checking")
  type: string                       // Account category: checking, savings, credit_card, investment
  balance: number                    // Current account balance in dollars
  account_number_last_four?: string  // Optional: Last 4 digits of account number (e.g., "1234")
  institution_name?: string          // Optional: Bank name (e.g., "Chase Bank")
  created_at: string                 // Timestamp when account was created
}

export default function AccountsPage() {
  
  // ═══════════════════════════════════════════════════════════════════
  // STATE MANAGEMENT
  // ═══════════════════════════════════════════════════════════════════
  
  // Next.js router for programmatic navigation (e.g., redirect to /login)
  const router = useRouter()
  
  // Authentication & Data Loading States
  const [loading, setLoading] = useState(true)  // True while checking if user is logged in
  const [user, setUser] = useState<{ id: string; name: string; email: string } | null>(null)  // Logged-in user info
  const [accounts, setAccounts] = useState<Account[]>([])  // Array of all user's accounts from database

  // Add Account Form States (controls the form inputs)
  const [showForm, setShowForm] = useState(false)  // Toggle to show/hide the "Add Account" form
  const [name, setName] = useState('')             // Form input: Account name
  const [accountType, setAccountType] = useState('checking')     // Form input: Account type (default: checking)
  const [balance, setBalance] = useState('')       // Form input: Current balance (as string, converted to number on submit)
  const [lastFour, setLastFour] = useState('')     // Form input: Last 4 digits of account number
  const [institution, setInstitution] = useState('')  // Form input: Bank/institution name
  const [saving, setSaving] = useState(false)      // True while saving new account to database (disables submit button)

  // ═══════════════════════════════════════════════════════════════════
  // LIFECYCLE - Run once when component mounts
  // ═══════════════════════════════════════════════════════════════════
  
  useEffect(() => {
    checkAuth()      // Verify user is logged in, redirect if not
    fetchAccounts()  // Load all accounts from database
  }, [])

  // ═══════════════════════════════════════════════════════════════════
  // AUTHENTICATION CHECK
  // ═══════════════════════════════════════════════════════════════════
  
  const checkAuth = async () => {
    // Create Supabase client instance to interact with backend
    const supabase = createClient()
    
    // Retrieve the current authentication session (if user is logged in)
    const { data: { session } } = await supabase.auth.getSession()

    // If no session exists, user is not logged in → redirect to login page
    if (!session) {
      router.push('/login')
      return
    }

    // Extract user's name from session metadata (Google OAuth provides full_name)
    // Fallback 1: Use email prefix if no full_name (e.g., "john" from "john@gmail.com")
    // Fallback 2: Use generic "User" if email is also missing
    const userName = session.user.user_metadata?.full_name || session.user.email?.split('@')[0] || 'User'
    const userEmail = session.user.email || ''
    const userId = session.user.id
    // Store user info in state to pass to sidebar component
    setUser({
      id: userId,
      name: userName,
      email: userEmail
    })
    
    // Authentication check complete, hide loading spinner
    setLoading(false)
  }

  // ═══════════════════════════════════════════════════════════════════
  // FETCH ACCOUNTS FROM DATABASE
  // ═══════════════════════════════════════════════════════════════════
  
  const fetchAccounts = async () => {
    // Create Supabase client to query database
    const supabase = createClient()
    
    // Get current user's session to access their user_id
    const { data: { session } } = await supabase.auth.getSession()
    
    // If user isn't logged in, exit early (shouldn't happen due to checkAuth)
    if (!session) return

    // Query the 'accounts' table in Supabase database
    // .select('*') = Get all columns
    // .eq('user_id', ...) = WHERE user_id = current user (RLS policy also enforces this)
    // .order('created_at', ...) = Sort by newest first (descending order)
    const { data, error } = await supabase
      .from('accounts')
      .select('*')
      .eq('user_id', session.user.id)
      .order('created_at', { ascending: false })

    // If query failed, log error to console and exit
    if (error) {
      console.error('Error fetching accounts:', error)
      return
    }

    // Update state with fetched accounts (or empty array if no accounts exist)
    setAccounts(data || [])
  }

  // ═══════════════════════════════════════════════════════════════════
  // ADD NEW ACCOUNT (FORM SUBMISSION)
  // ═══════════════════════════════════════════════════════════════════
  
  const handleSubmit = async (e: React.FormEvent) => {
    // Prevent default form behavior (page refresh)
    e.preventDefault()
    
    // Show loading state on submit button (disable it, show "Saving..." text)
    setSaving(true)

    // Create Supabase client to insert data
    const supabase = createClient()
    
    // Get current user's session to associate account with their user_id
    const { data: { session } } = await supabase.auth.getSession()
    
    // Safety check: exit if no session (shouldn't happen)
    if (!session) return

    // Insert new account into 'accounts' table
    // Supabase automatically generates id and created_at timestamp
    const { data, error } = await supabase
      .from('accounts')
      .insert({
        user_id: session.user.id,                   // Link account to current user
        name: name,                                  // Account name from form input
        type: accountType,                           // Account type from dropdown
        balance: parseFloat(balance) || 0,          // Convert string to number, default to 0 if invalid
        account_number_last_four: lastFour || null, // Last 4 digits or null if empty
        institution_name: institution || null,      // Bank name or null if empty
      })
      .select()  // Return the inserted row

    // If insert failed, show detailed error information
    if (error) {
      console.error('Error creating account:', error)
      console.error('Error details:', JSON.stringify(error, null, 2))
      alert(`Failed to create account: ${error.message || 'Unknown error'}`)
    } else {
      // Success! Reset all form fields to empty/default values
      console.log('Account created successfully:', data)
      setName('')
      setAccountType('checking')
      setBalance('')
      setLastFour('')
      setInstitution('')
      setShowForm(false)  // Hide the form
      
      // Refresh the accounts list to show the newly added account
      fetchAccounts()
    }

    // Hide loading state on submit button
    setSaving(false)
  }

  // ═══════════════════════════════════════════════════════════════════
  // DELETE ACCOUNT
  // ═══════════════════════════════════════════════════════════════════
  
  const deleteAccount = async (id: string) => {
    // Show browser confirmation dialog before deleting
    // If user clicks "Cancel", exit early
    if (!confirm('Are you sure you want to delete this account?')) return

    // Create Supabase client to delete data
    const supabase = createClient()
    
    // Delete the account from 'accounts' table where id matches
    // RLS policy ensures users can only delete their own accounts
    const { error } = await supabase
      .from('accounts')
      .delete()
      .eq('id', id)

    // If delete failed, show error alert
    if (error) {
      console.error('Error deleting account:', error)
      alert('Failed to delete account')
    } else {
      // Success! Refresh the accounts list (deleted account will be gone)
      fetchAccounts()
    }
  }

  // ═══════════════════════════════════════════════════════════════════
  // LOADING STATE - Show spinner while checking authentication
  // ═══════════════════════════════════════════════════════════════════
  
  if (loading) {
    return <div className="flex h-screen items-center justify-center">Loading...</div>
  }

  // ═══════════════════════════════════════════════════════════════════
  // RENDER UI
  // ═══════════════════════════════════════════════════════════════════

  return (
    // SidebarProvider wraps the entire page to manage sidebar open/close state
    <SidebarProvider>
      {/* Left sidebar with navigation */}
      <AppSidebar user={user || undefined} />
      
      {/* Main content area (everything to the right of sidebar) */}
      <SidebarInset>
        
        {/* ═══════════════════════════════════════════════════════════════ */}
        {/* HEADER - Breadcrumb navigation */}
        {/* ═══════════════════════════════════════════════════════════════ */}
        <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
          {/* Hamburger menu button to toggle sidebar (shows on mobile) */}
          <SidebarTrigger className="-ml-1" />
          
          {/* Vertical divider line */}
          <Separator orientation="vertical" className="mr-2 h-4" />
          
          {/* Breadcrumb trail: Dashboard > Accounts */}
          <Breadcrumb>
            <BreadcrumbList>
              {/* Link back to Dashboard (hidden on mobile to save space) */}
              <BreadcrumbItem className="hidden md:block">
                <BreadcrumbLink href="/">Dashboard</BreadcrumbLink>
              </BreadcrumbItem>
              
              {/* Separator arrow (hidden on mobile) */}
              <BreadcrumbSeparator className="hidden md:block" />
              
              {/* Current page (not clickable) */}
              <BreadcrumbItem>
                <BreadcrumbPage>Accounts</BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
        </header>

        {/* ═══════════════════════════════════════════════════════════════ */}
        {/* MAIN CONTENT */}
        {/* ═══════════════════════════════════════════════════════════════ */}
        <div className="flex flex-1 flex-col gap-4 p-4">
          

          {/* Page Title and Action Buttons */}
          <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
            <div>
              <h1 className="text-2xl font-bold">Accounts</h1>
              <p className="text-muted-foreground">Manage your bank accounts</p>
            </div>
            <div className="flex gap-2 mt-2 md:mt-0">
              {/* Connect Bank Button - Ready for Teller.io integration */}
              <Button 
                onClick={() => alert('Connect bank functionality - integrate Teller.io here')}
                variant="default"
              >
                🏦 Connect Bank
              </Button>

              {/* Toggle button: Shows "+ Add New" or "Cancel" based on form visibility */}
              <Button 
                onClick={() => setShowForm(!showForm)}
                variant="primary"
              >
                {showForm ? 'Cancel' : '+ Add New'}
              </Button>
            </div>
          </div>

          {/* ═══════════════════════════════════════════════════════════ */}
          {/* ADD ACCOUNT FORM (conditionally rendered when showForm = true) */}
          {/* ═══════════════════════════════════════════════════════════ */}
          {showForm && (
            <Card>
              <CardHeader>
                <CardTitle>Add New Account</CardTitle>
                <CardDescription>Enter your account details below</CardDescription>
              </CardHeader>
              <CardContent>
                {/* Form submits to handleSubmit function */}
                <form onSubmit={handleSubmit} className="space-y-4">
                  
                  {/* Account Name Input (Required) */}
                  <div className="grid gap-2">
                    <Label htmlFor="name">Account Name *</Label>
                    <Input
                      id="name"
                      placeholder="My Checking Account"
                      value={name}
                      onChange={(e) => setName(e.target.value)}  // Update state on every keystroke
                      required  // HTML5 validation: field cannot be empty
                    />
                  </div>

                  {/* Account Type Dropdown (Required) */}
                  <div className="grid gap-2">
                    <Label htmlFor="type">Account Type *</Label>
                    <Select value={accountType} onValueChange={setAccountType}>  {/* onValueChange updates state */}
                      <SelectTrigger>
                        <SelectValue />  {/* Shows currently selected value */}
                      </SelectTrigger>
                      <SelectContent>
                        {/* 4 predefined account types */}
                        <SelectItem value="checking">Checking</SelectItem>
                        <SelectItem value="savings">Savings</SelectItem>
                        <SelectItem value="credit_card">Credit Card</SelectItem>
                        <SelectItem value="investment">Investment</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  {/* Current Balance Input (Required, Number) */}
                  <div className="grid gap-2">
                    <Label htmlFor="balance">Current Balance *</Label>
                    <Input
                      id="balance"
                      type="number"      // HTML5 number input (allows decimals)
                      step="0.01"        // Allow 2 decimal places (e.g., 1000.50)
                      placeholder="1000.00"
                      value={balance}
                      onChange={(e) => setBalance(e.target.value)}
                      required
                    />
                  </div>

                  {/* Institution Name Input (Optional) */}
                  <div className="grid gap-2">
                    <Label htmlFor="institution">Institution (Optional)</Label>
                    <Input
                      id="institution"
                      placeholder="Chase Bank"
                      value={institution}
                      onChange={(e) => setInstitution(e.target.value)}
                    />
                  </div>

                  {/* Last 4 Digits Input (Optional, Max 4 characters) */}
                  <div className="grid gap-2">
                    <Label htmlFor="lastFour">Last 4 Digits (Optional)</Label>
                    <Input
                      id="lastFour"
                      placeholder="1234"
                      maxLength={4}  // Restrict input to 4 characters max
                      value={lastFour}
                      onChange={(e) => setLastFour(e.target.value)}
                    />
                  </div>

                  {/* Submit Button */}
                  <Button type="submit" disabled={saving} className="w-full">
                    {/* Show "Saving..." text when saving = true, otherwise "Add Account" */}
                    {saving ? 'Saving...' : '+ Add New'}
                  </Button>
                </form>
              </CardContent>
            </Card>
          )}

          {/* ═══════════════════════════════════════════════════════════ */}
          {/* ACCOUNTS GRID - Match Dashboard style */}
          <div className="rounded-xl border bg-card p-6 shadow-lg">
            
            {loading ? (
              <p className="text-sm text-muted-foreground">Loading accounts...</p>
            ) : accounts.length === 0 ? (
              <p className="text-sm text-muted-foreground">No accounts yet.</p>
            ) : (
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4 lg:max-w-8xl ">
                {accounts.map((account, index) => (
                  <AccountCard
                    key={account.id}
                    account={account}
                    index={index}
                  />
                ))}
              </div>
            )}
          </div>

          {/* ═══════════════════════════════════════════════════════════ */}
          {/* EMPTY STATE - Show when no accounts exist and form is hidden */}
          {/* ═══════════════════════════════════════════════════════════ */}
          {accounts.length === 0 && !showForm && (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <p className="text-muted-foreground">No accounts yet</p>
              
            </div>
          )}
        </div>
      </SidebarInset>
    </SidebarProvider>
  )
}
